# permissions for end users to edit virtualmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vmoperator
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachine-editor-role
rules:
- apiGroups:
  - core.vmoperator.io.core.vmoperator.io
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.vmoperator.io.core.vmoperator.io
  resources:
  - virtualmachines/status
  verbs:
  - get
